# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Categorical Deep Learning  # Name of your website
tagline: Categorical Deep Learning  # Set your preferred page title
description: An Algebraic Theory of Architectures  # Also used as a meta description
favicon: https://picsum.photos/32/32 # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
logo: https://picsum.photos/200 # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://www.categoricaldeeplearning.com # URL of your website
locale: en_GB # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: G-XXXXXXX # Google Analytics 4 measurement ID (optional). Remove it if not needed.
twitter:
  username: DigiMalayali # Used for SEO
image:
  path: https://picsum.photos/200 # Used for SEO
  type: jpeg # File format of image. Change according to your image. Supported types: https://en.wikipedia.org/wiki/Media_type#Common_examples
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge: false  # Set to 'true' or 'false' to enable / disable the badge
icon: ri:verified-badge-fill  # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
color: '#dfb221'  # Define the color of the badge
 
# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"    

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
